### ISSUE TITLE
Fullscreen on any Non-Main-Screen not possible

### ISSUE THREAD

**Issue by HohMac** [iaincollins/icarus#43]
The Terminal window will not go to Fullscreen on any other screen then the main screen.
Even when I pull the window to my second screen, when I click on the button to go to Fullscreen, the Terminal window will switch back to the main screen. It should be possible to choose on which monitor I want to have the Terminal window.

**Comment by HohMac** [comment]
I´m sorry, haven´t followed "RTFM" ;)

**Comment by splashythewhale** [comment]
@HohMac One trick you can use is to fullscreen the app and then use win+shift+arrow keys to move the full app to a separate monitor

**Comment by iaincollins** [comment]
Ugh yeah this is a pain to fix! I did sort of half try (unbelievably Windows does not have an API for this and you have to write your own logic to work out which display a window is on!) but didn't follow it up. It is annoying though.
