### ISSUE TITLE
Some station orbits are not properly rendered

### ISSUE THREAD

**Issue by splashythewhale** [iaincollins/icarus#45]
For example. In Vega System. Fort Dixon actually orbits the ELW (Tracy's Havan) and not the innermost rocky planet.

https://imgur.com/a/xRtAAT4

**Comment by iaincollins** [comment]
Thanks! Yes this is a known issue! I go into a bit on the forums, I've been working towards improving this but it's tricky as the game doesn't currently log enough data to make it possible to do this easily. I do have some ideas about it though…

(Sorry this got auto-closed.)
