### ISSUE TITLE
Full screen does not stay in secondary monitor

### ISSUE THREAD

**Issue by parduz** [iaincollins/icarus#46]
I keep the terminal on a secondary monitor. When i click on the "full screen" icon, the terminal moves to the primary one.

before:
![image](https://user-images.githubusercontent.com/9556348/216765053-680e6ce5-eec0-4227-bd39-c869fe506db0.png)

after:
![image](https://user-images.githubusercontent.com/9556348/216765073-4dd3fbf9-1086-4e87-9413-11ebe12eb788.png)

It should instead remain on the monitor where the windows currently is.

**Comment by splashythewhale** [comment]
@parduz One trick you can use is to fullscreen the app and then use win+shift+arrow keys to move the full app to a separate monitor

**Comment by iaincollins** [comment]
Sorry this got auto-closed.

More details in my reply on #43
