### ISSUE TITLE
System scan is one body behind

### ISSUE THREAD

**Issue by HalcyonSpectre** [iaincollins/icarus#50]
When scanning unmapped system latest planet doesn’t show up. E.g. after scanning 4 bodies only 3 show up.
Once system is fully scan you have to honk again for it to mark as completed in app, otherwise is stays at 90ish percent.

**Comment by HalcyonSpectre** [comment]
Seem like the latest update addressed the issue.

**Comment by iaincollins** [comment]
It's a little bit janky honestly in that there is a delay while data gets submitted to ESDM.

I did add some client code to try and fix this but I don't think I finished implementing it fully and sometimes you need to either (a) honk (in game) or (b) tap on the progress icon on the map in ICARUS Terminal to get it to refresh.
