### ISSUE TITLE
Launch not possible without error

### ISSUE THREAD

**Issue by Lithanie** [iaincollins/icarus#57]
I have the same problem that is evoked on this thread :
https://www.reddit.com/r/EliteDangerous/comments/1an5rrd/icarus_tool/

When I launch the Icarus Terminal an empty window appears for a split second and close instantly.
No error message or any event logged in Windows.

No compatibility mode or administrator mode is fixing the problem.
Tried disabling every antivirus, defender, firewall I had but the problem is still here.

Any way to get logs or info on this problem ?
I'm using Windows 10 22H2 Build 19045.4894

**Comment by iaincollins** [comment]
Sorry, I have no idea what's causing this and no way to replicate it. :-(

I suspect either AV software or that some core dependency, that is build into Windows, has been uninstalled at some point (either via Add / Remove Programs, by a third party installer for some other software that depended on them also but incorrectly removed them).

e.g. something like if Microsoft Edge or a C++ runtime library that ships with Windows has been removed.

If it used to work you could try adding and removing the program and seeing if the bundled Microsoft dependency checker embedded into the installer for ICARUS Terminal fixes this (it only catches some cases...) but if it's never worked I can't really help without having access to a system experiencing this issue, sorry.

It's possible Windows Event logs MIGHT have something useful. If anyone runs into this and is able to shed any light on this - e.g. an error message in logs or when trying to run it at the command line - please do comment / open a new issue / get in touch.
